name: platform_specific
description: Package that simplifies handling platform-specific operations and callbacks in your Dart/Flutter applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.24.3
  very_good_analysis: ^5.0.0+1
dependencies:
  universal_platform: ^1.0.0+1
